name: Validate

on:
  workflow_dispatch:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Docs Check
        run: |
          before=$(cat docs/cli/*.md | md5sum)
          go run main.go docs docs/cli
          after=$(cat docs/cli/*.md | md5sum)
          if [ "$before" != "$after" ]; then exit 1; fi
        shell: bash
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          args: --timeout=5m
          version: v1.38.0 # https://github.com/golangci/golangci-lint/releases
          skip-go-installation: true
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Go Mod Tidy
        run: test -z $(go mod tidy)
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Goreleaser Check
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Cache Modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test -cover -coverprofile=c.out -covermode=atomic -race -v ./...
      - name: Upload Codeclimate Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          prefix: github.com/lingrino/vaku/v2/
          coverageLocations: ${{ github.workspace }}/c.out:gocov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Upload Codecov Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./c.out
          fail_ci_if_error: true
